# This is specific GraphQL validator configuration file. It is introduced to support multiple
# frameworks in the same server instance and it is recommended. If this file cannot be found,
# the generic validator.yml will be loaded as a fallback.
---
# Enable request validation against the specification
enabled: true
# Log error message if validation error occurs
logError: true
