apijson:
  jdbcUrl: jdbc:mysql://${db.hostPort:localhost:3306}/${db.database:apijson}?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  username: ${db.username:apijson}
  password: ${db.username:apijson}
  parameters:
    maximumPoolSize: ${db.maximumPoolSize:1}

bbs:
  jdbcUrl: jdbc:mysql://${bbs.hostPort:localhost:3306}/${bbs.database:bbs}?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  username: ${bbs.username:apijson}
  password: ${bbs.username:apijson}
  parameters:
    maximumPoolSize: ${bbs.maximumPoolSize:1}
