@host=http://localhost:8083
@hybrid={{host}}/hybrid
@echo={{host}}/hybrid/gservice/echo
### 支持/hybrid/{service}/{action}
POST {{echo}}
Content-Type: application/json

{ "hello":"中文" }
### 兼容原rpc风格
POST {{hybrid}}

{
  "host": "xlongwei.com",
  "service": "gservice",
  "action": "echo",
  "version": "0.0.1",
  "data": { "hello":"中文" }
}
### 支持请求参数，host与version有默认值
POST {{hybrid}}?service=gservice&action=echo&test=%E6%B5%8B%E8%AF%95

{ "hello":"中文" }
### 支持表单提交，支持URL编码
POST {{hybrid}}/gservice/echo
Content-Type: application/x-www-form-urlencoded

param1=值1&参数2=值2&%E5%8F%82%E6%95%B03=%E5%80%BC3
### 支持文件上传
POST {{hybrid}}/gservice/echo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="readme.md"
Content-Type: text/plain

< ./readme.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--
### 兼容get请求里面的cmd参数
{{hybrid}}/gservice/echo?cmd={"host":"xlongwei.com","service":"gservice","action":"hello","version":"0.0.1","data":{"hello":"你好"}}
### hybrid风格指定host、version时，bodyMap会自动remove掉host、version，query参数会覆盖body同名参数
POST {{hybrid}}/gservice/echo?hello=world

{"host":"xlongwei.com","version":"0.0.1","hello":"你好"}
### enableRegistry
# @consul=https://api.xlongwei.com
@consul=http://115.28.229.158:8500
PUT {{consul}}/v1/agent/service/register
Host: localhost
Transfer-Encoding: chunked

{"ID":"10.11.218.43:com.xlongwei.gserver-3.0.1:8083","Name":"com.xlongwei.gserver-3.0.1","Tags":[""],"Address":"10.11.218.43","Port":8083,"Check":{"CheckID":"check-10.11.218.43:com.xlongwei.gserver-3.0.1:8083","DeregisterCriticalServiceAfter":"2m","TTL":"10s"}}
### lookupHealthService=/v1/health/service/{serviceName}
GET {{consul}}/v1/health/service/com.xlongwei.gserver-3.0.1?passing&wait=600s&index=0
# "Service": {
#       "ID": "10.11.218.43:com.xlongwei.gserver-3.0.1:8083",
#       "Service": "com.xlongwei.gserver-3.0.1",
#       "Tags": [
#         ""
#       ],
#       "Address": "10.11.218.43",
#       "Meta": null,
#       "Port": 8083,
#       "EnableTagOverride": false,
#       "CreateIndex": 7124,
#       "ModifyIndex": 7124
#     }
### unregisterService=/v1/agent/service/deregister/{serviceId}
PUT {{consul}}/v1/agent/service/deregister/10.11.218.43:com.xlongwei.gserver-3.0.1:8083

